# Generated by Django 4.2.6 on 2023-10-21 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paymant', models.CharField(choices=[('CASH,', 'CASH'), ('CARD', 'CARD')], default='CARD', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Costomer', to='costomer.costomer')),
                ('praduct', models.ManyToManyField(blank=True, related_name='Praduct', to='shop.praduct')),
            ],
        ),
    ]
